## A hacker's guide to Neural Networks

This notebook is a theoretical approach to breaking down the inner workings of neural networks into digestable parts to help gain a better inuition for how neural networks work. A neural network is twofold **forward propagation** and **backpropagation**. We'll break down forward propagation and backpropagation exploring each concept indepth including their biological inspiration and mathematical understanding; slowly building up to the bigger idea. I've found exploring each idea in-depth helps to better understand how these systems work. In essences, neural networks are a black box and the goal is to demystify these systems so you can better understand how they work.    

In [45]:
import numpy as np
import matplotlib.pyplot as plt

![Perceptron](./images/Perceptron.png)

In [7]:
inputs = [1.2, 5.1, 2.1] 
weights = [3.1, 2.1, 8.7]
bias = 3

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

35.7


In [25]:
# Dot product - multiplies each scalar element-wise then sums those scalars together
output = np.dot(weights, inputs) + bias
print(output)

35.7


![Multi-Linear_Perceptron](./images/Multi-Linear_Perceptron.png)

In [44]:
np.random.seed(42)

inputs = np.random.randn(5)
weights = np.random.randn(3, 5)
biases = np.random.randn(3)

output = np.dot(weights, inputs) + biases
print(output)

[ 0.78599378 -2.74494004 -0.92044729]


In [32]:
inputs

array([ 1.17115625, -1.16803526, -0.82160782,  0.92183037, -0.33256601])

In [38]:
inputs, inputs.shape

(array([ 1.17115625, -1.16803526, -0.82160782,  0.92183037, -0.33256601]),
 (5,))

In [39]:
weights, weights.shape

(array([[-0.1495665 , -0.14756567, -1.19343778,  0.52912856,  0.84744265],
        [-0.33508691,  1.40474206,  1.35984153, -0.29074424,  0.1959536 ],
        [ 0.87985141, -0.13661696, -1.098662  , -0.99735146, -0.06985282]]),
 (3, 5))