## Softmax Activation

In [9]:
# Exponential function
# y = e^x

# Euler's number
e = 2.718281828459045

# Where exponentiating to convert negatives to positives without loosing the meaning of negative values.
outputs = [4.8, 1.21, -2.385]
for i, value in enumerate(outputs):
    outputs[i] = e ** value

print(outputs)

[121.51041751873483, 3.353484652549023, 10.859062664920513]


In [10]:
# Normalization - produces a probability distribution where each value is divided by the sum of all the values.
normBase = sum(outputs)
normOutputs = outputs

for i, value in enumerate(outputs):
    normOutputs[i] = value / normBase

print(normOutputs)
print(sum(normOutputs))

[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


In [21]:
import numpy as np

# Input -> Exponentiate -> Normalize -> Output

outputs = [[4.8, 1.21, -2.385], 
           [8.9, -1.81, 0.2], 
           [1.41, 1.051, 0.026]]

expValues = np.exp(outputs)
normValues = expValues / np.sum(expValues, 
                                axis=1, # calculates the sum at dimension 1 or for each feature vector. 
                                keepdims=True) # keeps the same dimension as outputs

print(normValues)
print(np.sum(normValues, axis=1))

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]
[1. 1. 1.]


In [22]:
# Overflow prevention
# v = u - max u
np.max(outputs, axis=1, keepdims=True)

array([[4.8 ],
       [8.9 ],
       [1.41]])

## Calculating Loss with Categorical Cross-Entropy